# Generated by Django 4.2 on 2023-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ceneo_id',
            field=models.CharField(default=1234, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
