# Generated by Django 4.2 on 2023-04-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_product_ceneo_id_alter_review_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disadvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disadvantage', models.TextField(blank=True, default='', max_length=40, null=True)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disadvantages', to='scrapper.review')),
            ],
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.TextField(blank=True, default='', max_length=40, null=True)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='scrapper.review')),
            ],
        ),
    ]
