# Generated by Django 4.2 on 2023-05-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_review_advantages_review_disadvantages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='review',
            name='disadvantages',
        ),
        migrations.AlterField(
            model_name='advantages',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='scrapper.review'),
        ),
        migrations.AlterField(
            model_name='disadvantages',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disadvantages', to='scrapper.review'),
        ),
    ]
