# Generated by Django 4.2 on 2023-05-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_remove_review_advantages_remove_review_disadvantages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantages',
            old_name='reviews',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='disadvantages',
            old_name='reviews',
            new_name='review',
        ),
    ]
