# Generated by Django 4.2 on 2023-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0006_rename_reviews_advantages_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='advantage',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='disadvantages',
            name='disadvantage',
            field=models.TextField(default='', max_length=40),
        ),
    ]
