# Generated by Django 4.2 on 2023-05-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_alter_advantages_advantage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='advantage',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='disadvantages',
            name='disadvantage',
            field=models.TextField(max_length=40),
        ),
    ]
